import { CoreEvent } from '../../types';

export const AIEvents = {
  REQUEST_STARTED: CoreEvent.AI_REQUEST_STARTED,
  REQUEST_FINISHED: CoreEvent.AI_REQUEST_FINISHED,
  VALIDATION_STARTED: CoreEvent.AI_VALIDATION_STARTED,
  VALIDATION_FINISHED: CoreEvent.AI_VALIDATION_FINISHED,
  DECISION_CREATED: CoreEvent.AI_DECISION_CREATED,
  PROVIDER_CHANGED: CoreEvent.AI_PROVIDER_CHANGED
} as const;
