import { GeneratedFile } from './CodeGenerationTypes';

const LUCIDE_ICON_MAP: Record<string, string> = {
  home: 'Home',
  search: 'Search',
  settings: 'Settings',
  user: 'User',
  users: 'Users',
  chart: 'BarChart3',
  analytics: 'TrendingUp',
  dashboard: 'LayoutDashboard',
  notification: 'Bell',
  email: 'Mail',
  phone: 'Phone',
  menu: 'Menu',
  close: 'X',
  check: 'Check',
  arrow: 'ArrowRight',
  plus: 'Plus',
  edit: 'Edit',
  delete: 'Trash2',
  download: 'Download',
  upload: 'Upload',
  filter: 'Filter',
  calendar: 'Calendar',
  star: 'Star',
  heart: 'Heart',
  info: 'Info',
  warning: 'AlertTriangle',
  error: 'AlertCircle',
  success: 'CheckCircle',
  zap: 'Zap',
  shield: 'Shield',
  lock: 'Lock',
  globe: 'Globe',
  layers: 'Layers',
  cpu: 'Cpu',
  code: 'Code2',
  database: 'Database',
  server: 'Server'
};

export class AssetGenerator {
  /** Resolve a semantic icon name to its Lucide React import identifier */
  public resolveIcon(name: string): string {
    const key = name.toLowerCase().replace(/[^a-z]/g, '');
    return LUCIDE_ICON_MAP[key] || 'Star';
  }

  /** Generate the lucide-react import statement for a set of icons */
  public generateIconImport(iconNames: string[]): string {
    const unique = [...new Set(iconNames)].sort();
    if (unique.length === 0) return '';
    return `import { ${unique.join(', ')} } from 'lucide-react';`;
  }

  /** Generate SVG placeholder for illustration */
  public generateSVGPlaceholder(label: string, width = 200, height = 160): string {
    const escaped = label.replace(/[<>&"]/g, '');
    return `
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="${escaped} illustration">
  <rect width="${width}" height="${height}" rx="12" fill="#F1F5F9"/>
  <rect x="${Math.floor(width / 2 - 28)}" y="${Math.floor(height / 2 - 28)}" width="56" height="56" rx="12" fill="#E2E8F0"/>
  <text x="${Math.floor(width / 2)}" y="${height - 16}" text-anchor="middle" font-family="Inter, sans-serif" font-size="11" fill="#94A3B8">${escaped}</text>
</svg>`.trim();
  }

  /** Generate an image placeholder component for public-folder assets */
  public generateImagePlaceholder(name: string): string {
    return `
export function ${name}Placeholder() {
  return (
    <div
      className="w-full h-40 bg-slate-100 rounded-xl flex items-center justify-center text-slate-400 text-sm font-medium border border-dashed border-slate-300"
      aria-label="${name} image placeholder"
    >
      <span>${name}</span>
    </div>
  );
}`.trim();
  }

  /** Generate the global asset placeholder file */
  public generateAssetPlaceholderFile(): GeneratedFile {
    return {
      path: 'src/assets/placeholders.tsx',
      language: 'typescript',
      type: 'asset',
      content: `
import React from 'react';

/**
 * Asset Placeholders
 * Generated by AI Code Generation Engine (Phase 9)
 * Replace each placeholder with your real assets.
 */

export function HeroIllustration() {
  return (
    <svg width="480" height="320" viewBox="0 0 480 320" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <rect width="480" height="320" rx="20" fill="rgba(255,255,255,0.08)"/>
      <rect x="96" y="64" width="288" height="192" rx="12" fill="rgba(255,255,255,0.12)"/>
      <circle cx="240" cy="160" r="56" fill="rgba(255,255,255,0.2)"/>
      <path d="M220 160 L240 140 L260 160 L240 180 Z" fill="rgba(255,255,255,0.6)"/>
    </svg>
  );
}

export function EmptyStateSVG({ label = 'No data' }: { label?: string }) {
  return (
    <div className="flex flex-col items-center justify-center gap-4 py-16 text-slate-400">
      <svg width="80" height="80" viewBox="0 0 80 80" fill="none" aria-hidden="true">
        <rect width="80" height="80" rx="16" fill="#F1F5F9"/>
        <path d="M24 56 L40 24 L56 56 Z" fill="#E2E8F0"/>
      </svg>
      <p className="text-sm font-medium">{label}</p>
    </div>
  );
}
`.trim()
    };
  }
}
