import { CoreEvent } from '../../types';

export const CodeEvents = {
  STARTED: CoreEvent.CODEGEN_STARTED,
  IR_CREATED: CoreEvent.CODEGEN_IR_CREATED,
  COMPONENT_CREATED: CoreEvent.CODEGEN_COMPONENT_CREATED,
  VALIDATION_STARTED: CoreEvent.CODEGEN_VALIDATION_STARTED,
  VALIDATION_FINISHED: CoreEvent.CODEGEN_VALIDATION_FINISHED,
  FINISHED: CoreEvent.CODEGEN_FINISHED,
  FAILED: CoreEvent.CODEGEN_FAILED
} as const;
