import { GeneratedFile } from './CodeGenerationTypes';
import { StyleGenerator } from './StyleGenerator';

const styleGen = new StyleGenerator();

function buildComponentFile(
  name: string,
  semanticTag: string,
  ariaLabel: string,
  classes: string,
  contentBody: string,
  propsType: string,
  propsDefault: string
): GeneratedFile {
  const content = `
import React from 'react';

export interface ${name}Props {
${propsType}
}

/**
 * ${name}
 * Generated by AI Code Generation Engine (Phase 9)
 */
export function ${name}({ ${propsDefault} }: ${name}Props) {
  return (
    <${semanticTag}
      className="${classes}"
      aria-label="${ariaLabel}"
    >
${contentBody}
    </${semanticTag}>
  );
}

export default ${name};
`.trim();

  return {
    path: `src/components/${name}.tsx`,
    content,
    language: 'typescript',
    type: 'component'
  };
}

export class ComponentGenerator {
  public generateAllComponents(): GeneratedFile[] {
    return [
      this.generateNavbar(),
      this.generateHero(),
      this.generateButton(),
      this.generateCard(),
      this.generateFeatureGrid(),
      this.generateSidebar(),
      this.generateFooter(),
      this.generateInput(),
      this.generateModal(),
      this.generateTable()
    ];
  }

  private generateNavbar(): GeneratedFile {
    const classes = styleGen.buildTailwindClassString(
      styleGen.deriveTailwindClasses('Navbar', {})
    );
    return buildComponentFile(
      'Navbar',
      'nav',
      'Main navigation',
      classes,
      `      <div className="flex items-center gap-2">
        <span className="w-8 h-8 rounded-lg bg-blue-600 flex items-center justify-center">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <rect x="2" y="2" width="5" height="5" rx="1" fill="white"/>
            <rect x="9" y="2" width="5" height="5" rx="1" fill="white" opacity="0.7"/>
            <rect x="2" y="9" width="5" height="5" rx="1" fill="white" opacity="0.7"/>
            <rect x="9" y="9" width="5" height="5" rx="1" fill="white" opacity="0.4"/>
          </svg>
        </span>
        <span className="text-base font-semibold text-slate-900 dark:text-white">{logoText}</span>
      </div>
      <div className="flex items-center gap-3">
        {children}
      </div>`,
      `  logoText?: string;\n  children?: React.ReactNode;`,
      `logoText = 'App', children`
    );
  }

  private generateHero(): GeneratedFile {
    const classes = styleGen.buildTailwindClassString(
      styleGen.deriveTailwindClasses('Hero', {})
    );
    return buildComponentFile(
      'Hero',
      'section',
      'Hero section',
      classes,
      `      <div className="absolute inset-0 opacity-20 pointer-events-none" aria-hidden="true">
        <div className="w-[400px] h-[400px] rounded-full bg-white/30 absolute -top-32 -right-24 blur-3xl" />
      </div>
      <div className="relative z-10 max-w-2xl mx-auto text-center">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">{heading}</h1>
        <p className="text-lg md:text-xl text-blue-100 mb-8">{subtext}</p>
        {children}
      </div>`,
      `  heading?: string;\n  subtext?: string;\n  children?: React.ReactNode;`,
      `heading = 'Welcome', subtext = 'Your new application', children`
    );
  }

  private generateButton(): GeneratedFile {
    const content = `
import React from 'react';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface ButtonProps {
  label?: string;
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  loading?: boolean;
  onClick?: () => void;
  children?: React.ReactNode;
  type?: 'button' | 'submit' | 'reset';
  className?: string;
  'aria-label'?: string;
}

const variantClasses: Record<ButtonVariant, string> = {
  primary: 'bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white shadow-sm',
  secondary: 'bg-slate-100 hover:bg-slate-200 active:bg-slate-300 text-slate-900 dark:bg-slate-800 dark:hover:bg-slate-700 dark:text-white',
  ghost: 'bg-transparent hover:bg-slate-100 active:bg-slate-200 text-slate-700 dark:text-slate-300 dark:hover:bg-slate-800',
  danger: 'bg-red-600 hover:bg-red-700 active:bg-red-800 text-white shadow-sm'
};

const sizeClasses: Record<ButtonSize, string> = {
  sm: 'px-3 py-1.5 text-xs rounded-md',
  md: 'px-5 py-2.5 text-sm rounded-lg',
  lg: 'px-7 py-3.5 text-base rounded-xl'
};

/**
 * Button
 * Generated by AI Code Generation Engine (Phase 9)
 */
export function Button({
  label,
  variant = 'primary',
  size = 'md',
  disabled = false,
  loading = false,
  onClick,
  children,
  type = 'button',
  className = '',
  'aria-label': ariaLabel
}: ButtonProps) {
  const base = 'inline-flex items-center justify-center gap-2 font-semibold transition-all duration-150 focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed';

  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled || loading}
      aria-label={ariaLabel || label}
      aria-busy={loading}
      className={\`\${base} \${variantClasses[variant]} \${sizeClasses[size]} \${className}\`}
    >
      {loading && (
        <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24" aria-hidden="true">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
        </svg>
      )}
      {children || label}
    </button>
  );
}

export default Button;
`.trim();

    return {
      path: 'src/components/Button.tsx',
      content,
      language: 'typescript',
      type: 'component'
    };
  }

  private generateCard(): GeneratedFile {
    const classes = styleGen.buildTailwindClassString(
      styleGen.deriveTailwindClasses('Card', {})
    );
    return buildComponentFile(
      'Card',
      'article',
      'Content card',
      classes,
      `      {title && (
        <h3 className="text-base font-semibold text-slate-900 dark:text-white mb-1">{title}</h3>
      )}
      {description && (
        <p className="text-sm text-slate-500 dark:text-slate-400">{description}</p>
      )}
      {children}`,
      `  title?: string;\n  description?: string;\n  children?: React.ReactNode;`,
      `title, description, children`
    );
  }

  private generateFeatureGrid(): GeneratedFile {
    const classes = styleGen.buildTailwindClassString(
      styleGen.deriveTailwindClasses('FeatureGrid', {})
    );
    return buildComponentFile(
      'FeatureGrid',
      'section',
      'Feature grid',
      classes,
      `      {children}`,
      `  children?: React.ReactNode;`,
      `children`
    );
  }

  private generateSidebar(): GeneratedFile {
    const classes = styleGen.buildTailwindClassString(
      styleGen.deriveTailwindClasses('Sidebar', {})
    );
    return buildComponentFile(
      'Sidebar',
      'aside',
      'Sidebar navigation',
      classes,
      `      {header && (
        <div className="px-4 pb-4 border-b border-slate-800 mb-4">
          <span className="text-sm font-semibold text-white">{header}</span>
        </div>
      )}
      <div className="flex-1 overflow-y-auto px-3 space-y-1">
        {children}
      </div>`,
      `  header?: string;\n  children?: React.ReactNode;`,
      `header, children`
    );
  }

  private generateFooter(): GeneratedFile {
    const classes = styleGen.buildTailwindClassString(
      styleGen.deriveTailwindClasses('Footer', {})
    );
    return buildComponentFile(
      'Footer',
      'footer',
      'Page footer',
      classes,
      `      <div className="flex flex-col md:flex-row items-center justify-between gap-2">
        <span>{copyright}</span>
        <div className="flex items-center gap-4">
          {children}
        </div>
      </div>`,
      `  copyright?: string;\n  children?: React.ReactNode;`,
      `copyright = '© 2026 All rights reserved.', children`
    );
  }

  private generateInput(): GeneratedFile {
    const content = `
import React from 'react';

export interface InputProps {
  label?: string;
  placeholder?: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  type?: string;
  disabled?: boolean;
  required?: boolean;
  error?: string;
  id?: string;
  className?: string;
}

/**
 * Input
 * Generated by AI Code Generation Engine (Phase 9)
 */
export function Input({
  label,
  placeholder,
  value,
  onChange,
  type = 'text',
  disabled = false,
  required = false,
  error,
  id,
  className = ''
}: InputProps) {
  const inputId = id || (label ? label.toLowerCase().replace(/\\s/g, '-') : 'input');

  return (
    <div className={\`flex flex-col gap-1 \${className}\`}>
      {label && (
        <label
          htmlFor={inputId}
          className="text-sm font-medium text-slate-700 dark:text-slate-300"
        >
          {label}
          {required && <span className="ml-1 text-red-500" aria-hidden="true">*</span>}
        </label>
      )}
      <input
        id={inputId}
        type={type}
        placeholder={placeholder}
        value={value}
        onChange={onChange}
        disabled={disabled}
        required={required}
        aria-required={required}
        aria-invalid={!!error}
        aria-describedby={error ? \`\${inputId}-error\` : undefined}
        className={[
          'w-full px-4 py-2 rounded-lg border text-sm transition-all outline-none',
          'bg-white dark:bg-slate-900',
          'text-slate-900 dark:text-slate-100',
          'placeholder:text-slate-400',
          error
            ? 'border-red-400 focus:ring-2 focus:ring-red-500/30'
            : 'border-slate-300 dark:border-slate-700 focus:ring-2 focus:ring-blue-500 focus:border-transparent',
          disabled ? 'opacity-50 cursor-not-allowed' : ''
        ].join(' ')}
      />
      {error && (
        <span id={\`\${inputId}-error\`} role="alert" className="text-xs text-red-500 mt-0.5">
          {error}
        </span>
      )}
    </div>
  );
}

export default Input;
`.trim();

    return {
      path: 'src/components/Input.tsx',
      content,
      language: 'typescript',
      type: 'component'
    };
  }

  private generateModal(): GeneratedFile {
    const content = `
import React, { useEffect, useRef } from 'react';

export interface ModalProps {
  open: boolean;
  onClose?: () => void;
  title?: string;
  children?: React.ReactNode;
  maxWidth?: 'sm' | 'md' | 'lg' | 'xl';
}

const maxWidthClasses = {
  sm: 'max-w-sm',
  md: 'max-w-md',
  lg: 'max-w-lg',
  xl: 'max-w-xl'
};

/**
 * Modal
 * Generated by AI Code Generation Engine (Phase 9)
 */
export function Modal({ open, onClose, title, children, maxWidth = 'md' }: ModalProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const focusable = dialogRef.current?.querySelectorAll<HTMLElement>(
      'a, button, input, textarea, select, [tabindex]:not([tabindex="-1"])'
    );
    if (open && focusable && focusable.length > 0) {
      focusable[0].focus();
    }
  }, [open]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      onClose?.();
    }
  };

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose?.(); }}
    >
      <dialog
        ref={dialogRef}
        open={open}
        onKeyDown={handleKeyDown}
        aria-modal="true"
        aria-labelledby="modal-title"
        className={\`relative w-full \${maxWidthClasses[maxWidth]} bg-white dark:bg-slate-900 rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-700 p-6 outline-none\`}
      >
        <div className="flex items-center justify-between mb-4">
          {title && (
            <h2 id="modal-title" className="text-lg font-semibold text-slate-900 dark:text-white">
              {title}
            </h2>
          )}
          <button
            type="button"
            onClick={onClose}
            aria-label="Close modal"
            className="ml-auto p-1.5 rounded-md text-slate-400 hover:text-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path d="M12 4L4 12M4 4l8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
            </svg>
          </button>
        </div>
        <div>{children}</div>
      </dialog>
    </div>
  );
}

export default Modal;
`.trim();

    return {
      path: 'src/components/Modal.tsx',
      content,
      language: 'typescript',
      type: 'component'
    };
  }

  private generateTable(): GeneratedFile {
    const content = `
import React from 'react';

export interface TableColumn<T = Record<string, unknown>> {
  key: string;
  header: string;
  render?: (value: unknown, row: T) => React.ReactNode;
  align?: 'left' | 'center' | 'right';
}

export interface TableProps<T = Record<string, unknown>> {
  columns: TableColumn<T>[];
  data: T[];
  caption?: string;
  loading?: boolean;
  emptyText?: string;
}

/**
 * Table
 * Generated by AI Code Generation Engine (Phase 9)
 */
export function Table<T extends Record<string, unknown>>({
  columns,
  data,
  caption,
  loading = false,
  emptyText = 'No data available'
}: TableProps<T>) {
  return (
    <div className="w-full overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700">
      <table className="w-full text-sm" role="grid">
        {caption && <caption className="sr-only">{caption}</caption>}
        <thead>
          <tr className="bg-slate-50 dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700">
            {columns.map((col) => (
              <th
                key={col.key}
                scope="col"
                className={\`px-4 py-3 text-\${col.align || 'left'} text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400\`}
              >
                {col.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
          {loading ? (
            <tr>
              <td colSpan={columns.length} className="px-4 py-12 text-center text-slate-400">
                <div className="flex items-center justify-center gap-2">
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24" aria-hidden="true">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Loading...
                </div>
              </td>
            </tr>
          ) : data.length === 0 ? (
            <tr>
              <td colSpan={columns.length} className="px-4 py-12 text-center text-slate-400">{emptyText}</td>
            </tr>
          ) : data.map((row, i) => (
            <tr
              key={i}
              className="bg-white dark:bg-slate-900 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
            >
              {columns.map((col) => (
                <td
                  key={col.key}
                  className={\`px-4 py-3 text-\${col.align || 'left'} text-slate-700 dark:text-slate-300\`}
                >
                  {col.render ? col.render(row[col.key], row) : String(row[col.key] ?? '')}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default Table;
`.trim();

    return {
      path: 'src/components/Table.tsx',
      content,
      language: 'typescript',
      type: 'component'
    };
  }
}
