import { IRTree, IRNode, GeneratedFile } from './CodeGenerationTypes';

export class LayoutGenerator {
  public generatePageLayouts(irTree: IRTree): GeneratedFile[] {
    return [
      this.generateMainPage(irTree),
      this.generateAppWrapper(irTree)
    ];
  }

  private generateMainPage(irTree: IRTree): GeneratedFile {
    const { root } = irTree;

    const imports = this.derivePageImports(root);
    const bodyJSX = this.renderIRNodeAsJSX(root, 2);

    const content = `
import React from 'react';
${imports}

/**
 * Main Application Page
 * Generated by AI Code Generation Engine (Phase 9)
 * Source: VisualDesignModel → IntermediateRepresentation → LayoutGenerator
 */
export default function MainPage() {
  return (
${bodyJSX}
  );
}
`.trim();

    return {
      path: 'src/pages/index.tsx',
      content,
      language: 'typescript',
      type: 'page'
    };
  }

  private generateAppWrapper(_irTree: IRTree): GeneratedFile {
    const content = `
import React from 'react';
import './styles/globals.css';
import MainPage from './pages/index';

/**
 * App Root
 * Generated by AI Code Generation Engine (Phase 9)
 */
export default function App() {
  return (
    <React.StrictMode>
      <div id="app-root" className="min-h-screen bg-slate-50 dark:bg-slate-950 font-sans antialiased">
        <MainPage />
      </div>
    </React.StrictMode>
  );
}
`.trim();

    return {
      path: 'src/App.tsx',
      content,
      language: 'typescript',
      type: 'page'
    };
  }

  private derivePageImports(root: IRNode): string {
    const componentTypes = this.collectComponentTypes(root);
    const knownComponents = new Set(['Navbar', 'Hero', 'Card', 'FeatureGrid', 'Footer', 'Sidebar', 'Button', 'Input', 'Modal', 'Table']);
    const lines: string[] = [];

    for (const type of componentTypes) {
      if (knownComponents.has(type)) {
        lines.push(`import { ${type} } from '../components/${type}';`);
      }
    }

    return lines.join('\n');
  }

  private collectComponentTypes(node: IRNode, acc = new Set<string>()): Set<string> {
    acc.add(node.componentType);
    for (const child of node.children || []) {
      this.collectComponentTypes(child, acc);
    }
    return acc;
  }

  private renderIRNodeAsJSX(node: IRNode, indent: number): string {
    const pad = ' '.repeat(indent * 2);
    const knownComponents = new Set(['Navbar', 'Hero', 'Card', 'FeatureGrid', 'Footer', 'Sidebar', 'Button', 'Input', 'Modal', 'Table']);

    const tag = knownComponents.has(node.componentType)
      ? node.componentType
      : node.accessibility?.semanticTag || 'div';

    const classList = [...new Set(node.tailwindClasses || [])].join(' ');
    const classAttr = classList ? ` className="${classList}"` : '';

    const extraProps = this.buildExtraProps(node);

    if (node.children && node.children.length > 0) {
      const childrenJSX = node.children
        .map((child) => this.renderIRNodeAsJSX(child, indent + 1))
        .join('\n');
      return `${pad}<${tag}${classAttr}${extraProps}>\n${childrenJSX}\n${pad}</${tag}>`;
    } else {
      return `${pad}<${tag}${classAttr}${extraProps} />`;
    }
  }

  private buildExtraProps(node: IRNode): string {
    const parts: string[] = [];
    if (node.accessibility?.ariaLabel) {
      parts.push(`aria-label="${node.accessibility.ariaLabel}"`);
    }
    if (node.props?.label && node.componentType === 'Button') {
      parts.push(`label="${node.props.label}"`);
    }
    if (node.props?.heading && node.componentType === 'Hero') {
      parts.push(`heading="${node.props.heading}"`);
    }
    if (node.props?.subtext && node.componentType === 'Hero') {
      parts.push(`subtext="${node.props.subtext}"`);
    }
    if (node.props?.logoText && node.componentType === 'Navbar') {
      parts.push(`logoText="${node.props.logoText}"`);
    }
    if (node.props?.copyright && node.componentType === 'Footer') {
      parts.push(`copyright="${node.props.copyright}"`);
    }
    return parts.length > 0 ? ' ' + parts.join(' ') : '';
  }
}
