import { GeneratedFile } from './CodeGenerationTypes';
import { StyleGenerator } from './StyleGenerator';

const styleGen = new StyleGenerator();

export class ProjectBuilder {
  public buildProjectFiles(): GeneratedFile[] {
    return [
      this.generatePackageJson(),
      this.generateTsConfig(),
      this.generateNextConfig(),
      this.generateReadme(),
      this.generateGlobalCSS(),
      this.generateIndexHTML()
    ];
  }

  private generatePackageJson(): GeneratedFile {
    const content = JSON.stringify(
      {
        name: 'generated-app',
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          next: '^14.2.0',
          react: '^18.3.0',
          'react-dom': '^18.3.0',
          'lucide-react': '^0.363.0'
        },
        devDependencies: {
          typescript: '^5.4.0',
          '@types/node': '^20.0.0',
          '@types/react': '^18.3.0',
          '@types/react-dom': '^18.3.0',
          tailwindcss: '^3.4.0',
          autoprefixer: '^10.4.0',
          postcss: '^8.4.0',
          eslint: '^8.57.0',
          'eslint-config-next': '14.2.0'
        }
      },
      null,
      2
    );

    return {
      path: 'package.json',
      content,
      language: 'json',
      type: 'config'
    };
  }

  private generateTsConfig(): GeneratedFile {
    const content = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: {
            '@/*': ['./src/*'],
            '@/tokens': ['./src/tokens/index'],
            '@/components': ['./src/components']
          }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      },
      null,
      2
    );

    return {
      path: 'tsconfig.json',
      content,
      language: 'json',
      type: 'config'
    };
  }

  private generateNextConfig(): GeneratedFile {
    const content = `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: []
  }
};

module.exports = nextConfig;
`.trim();

    return {
      path: 'next.config.js',
      content,
      language: 'javascript',
      type: 'config'
    };
  }

  private generateGlobalCSS(): GeneratedFile {
    return {
      path: 'src/styles/globals.css',
      content: [
        `@tailwind base;`,
        `@tailwind components;`,
        `@tailwind utilities;`,
        '',
        styleGen.generateGlobalCSS()
      ].join('\n'),
      language: 'css',
      type: 'style'
    };
  }

  private generateReadme(): GeneratedFile {
    const content = `
# Generated Application

> Generated by **AI Orchestration Platform — Phase 9: Code Generation Engine**

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view the application.

## Project Structure

\`\`\`
src/
  components/     # Reusable React components
  pages/          # Next.js App Router pages
  styles/         # Global CSS and Tailwind configuration
  tokens/         # Design tokens (colors, typography, spacing)
  assets/         # Static assets and SVG placeholders
\`\`\`

## Design System

Design tokens are defined in \`src/tokens/index.ts\` and integrated with Tailwind CSS via \`tailwind.config.js\`.
All components consume these central tokens to ensure visual consistency.

## Accessibility

All components follow WCAG 2.1 AA guidelines:
- Semantic HTML elements
- ARIA labels and roles
- Keyboard navigation support
- Focus-visible ring styles

---
*Generated by the AI Code Generation Engine. Do not edit generated files directly — re-generate from the design model.*
`.trim();

    return {
      path: 'README.md',
      content,
      language: 'markdown',
      type: 'config'
    };
  }

  private generateIndexHTML(): GeneratedFile {
    const content = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Generated Application — AI Code Generation Engine Phase 9" />
    <title>Generated App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`;

    return {
      path: 'index.html',
      content,
      language: 'html',
      type: 'config'
    };
  }
}
