import { IRNode } from './CodeGenerationTypes';

export class StyleGenerator {
  public generateInlineStyles(node: IRNode): Record<string, string> {
    const styles: Record<string, string> = {};

    if (node.styles.backgroundColor) {
      styles.backgroundColor = node.styles.backgroundColor;
    }
    if (node.styles.color) {
      styles.color = node.styles.color;
    }
    if (node.styles.borderRadius) {
      styles.borderRadius = node.styles.borderRadius;
    }

    return styles;
  }

  public generateGlobalCSS(): string {
    return `
/* Global CSS — Generated by AI Code Generation Engine (Phase 9) */

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

:root {
  --color-primary: #3B82F6;
  --color-primary-hover: #2563EB;
  --color-secondary: #1E293B;
  --color-accent: #F59E0B;
  --color-surface: #FFFFFF;
  --color-surface-subtle: #F8FAFC;
  --color-background: #F8FAFC;
  --color-border: #E2E8F0;
  --color-text: #0F172A;
  --color-text-muted: #64748B;
  --font-family-base: 'Inter', sans-serif;
  --radius-sm: 0.25rem;
  --radius-md: 0.375rem;
  --radius-lg: 0.5rem;
  --radius-xl: 0.75rem;
  --radius-2xl: 1rem;
  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);
  --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);
  --transition-default: 150ms cubic-bezier(0.4, 0, 0.2, 1);
}

*, *::before, *::after {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: var(--font-family-base);
  background-color: var(--color-background);
  color: var(--color-text);
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}

/* Glassmorphism Utilities */
.glass {
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid rgba(255, 255, 255, 0.15);
}

.glass-dark {
  background: rgba(15, 23, 42, 0.65);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border: 1px solid rgba(255, 255, 255, 0.08);
}

/* Focus Ring */
*:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 2px;
  border-radius: var(--radius-sm);
}

/* Scroll */
::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}
::-webkit-scrollbar-track {
  background: var(--color-surface-subtle);
}
::-webkit-scrollbar-thumb {
  background: var(--color-border);
  border-radius: 999px;
}
::-webkit-scrollbar-thumb:hover {
  background: var(--color-text-muted);
}
`.trim();
  }

  public buildTailwindClassString(classes: string[]): string {
    return [...new Set(classes)].join(' ');
  }

  public deriveTailwindClasses(type: string, _props: Record<string, any>): string[] {
    const base: string[] = ['w-full'];

    switch (type) {
      case 'Navbar':
      case 'Header':
        return [...base, 'sticky', 'top-0', 'z-50', 'bg-white/80', 'dark:bg-slate-900/80', 'backdrop-blur', 'border-b', 'border-slate-200', 'dark:border-slate-800', 'px-6', 'py-4', 'flex', 'items-center', 'justify-between'];
      case 'Hero':
        return [...base, 'relative', 'overflow-hidden', 'py-20', 'px-8', 'bg-gradient-to-br', 'from-blue-600', 'via-indigo-600', 'to-violet-700', 'text-white', 'rounded-2xl', 'shadow-2xl'];
      case 'Card':
        return [...base, 'p-6', 'bg-white', 'dark:bg-slate-800', 'rounded-xl', 'shadow-sm', 'hover:shadow-md', 'transition-shadow', 'duration-200', 'border', 'border-slate-100', 'dark:border-slate-700'];
      case 'FeatureGrid':
        return [...base, 'grid', 'grid-cols-1', 'sm:grid-cols-2', 'lg:grid-cols-3', 'gap-6'];
      case 'Button':
        return ['inline-flex', 'items-center', 'justify-center', 'gap-2', 'px-5', 'py-2.5', 'bg-blue-600', 'hover:bg-blue-700', 'active:bg-blue-800', 'text-white', 'text-sm', 'font-semibold', 'rounded-lg', 'shadow-sm', 'transition-all', 'duration-150', 'focus-visible:ring-2', 'focus-visible:ring-blue-500', 'focus-visible:ring-offset-2'];
      case 'Input':
        return [...base, 'px-4', 'py-2', 'bg-white', 'dark:bg-slate-900', 'border', 'border-slate-300', 'dark:border-slate-700', 'rounded-lg', 'text-sm', 'text-slate-900', 'dark:text-slate-100', 'placeholder:text-slate-400', 'focus:ring-2', 'focus:ring-blue-500', 'focus:border-transparent', 'outline-none', 'transition'];
      case 'Sidebar':
        return ['h-full', 'w-64', 'flex-shrink-0', 'flex', 'flex-col', 'bg-slate-900', 'text-slate-300', 'border-r', 'border-slate-800', 'overflow-y-auto', 'py-4'];
      case 'Footer':
        return [...base, 'mt-auto', 'py-8', 'px-6', 'bg-slate-900', 'dark:bg-slate-950', 'text-slate-400', 'text-sm', 'border-t', 'border-slate-800'];
      case 'Modal':
        return ['fixed', 'inset-0', 'z-50', 'flex', 'items-center', 'justify-center', 'p-4', 'bg-black/50', 'backdrop-blur-sm'];
      case 'Table':
        return [...base, 'overflow-hidden', 'rounded-xl', 'border', 'border-slate-200', 'dark:border-slate-700', 'divide-y', 'divide-slate-200', 'dark:divide-slate-700'];
      default:
        return [...base, 'p-4', 'rounded-lg'];
    }
  }
}
