import { VisualDesignModel } from '../design/DesignTypes';
import { GeneratedFile } from './CodeGenerationTypes';

export class TokenGenerator {
  public generateTokens(visualModel: VisualDesignModel | null): GeneratedFile[] {
    const activeOption = visualModel?.activeOption || visualModel;
    const colors = activeOption?.colorTokens || {
      primary: '#3B82F6',
      primaryHover: '#2563EB',
      secondary: '#1E293B',
      accent: '#F59E0B',
      surface: '#FFFFFF',
      surfaceSubtle: '#F8FAFC',
      background: '#F8FAFC',
      border: '#E2E8F0',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      information: '#3B82F6',
      text: '#0F172A',
      textMuted: '#64748B'
    };

    const headingFont = activeOption?.typographyScale?.fontFamilyHeadings || 'Inter, sans-serif';
    const bodyFont = activeOption?.typographyScale?.fontFamilyBody || 'Inter, sans-serif';

    const indexContent = `
/**
 * Design Tokens Central Registry
 * Generated by AI Code Generation Engine (Phase 9)
 */

export const colors = {
  primary: '${colors.primary}',
  primaryHover: '${colors.primaryHover || colors.primary}',
  secondary: '${colors.secondary}',
  accent: '${colors.accent}',
  surface: '${colors.surface}',
  surfaceSubtle: '${colors.surfaceSubtle || '#F8FAFC'}',
  background: '${colors.background}',
  border: '${colors.border}',
  success: '${colors.success || '#10B981'}',
  warning: '${colors.warning || '#F59E0B'}',
  danger: '${colors.danger || '#EF4444'}',
  text: '${colors.text}',
  textMuted: '${colors.textMuted || '#64748B'}'
} as const;

export const typography = {
  fontFamilyHeadings: '${headingFont}',
  fontFamilyBody: '${bodyFont}',
  sizes: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem'
  },
  weights: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700
  }
} as const;

export const spacing = {
  xs: '0.25rem',
  sm: '0.5rem',
  md: '1rem',
  lg: '1.5rem',
  xl: '2rem',
  '2xl': '3rem',
  '3xl': '4rem'
} as const;

export const radius = {
  none: '0px',
  sm: '0.25rem',
  md: '0.375rem',
  lg: '0.5rem',
  xl: '0.75rem',
  '2xl': '1rem',
  full: '9999px'
} as const;

export const shadows = {
  sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
  md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
  xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)'
} as const;

export const breakpoints = {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px'
} as const;

export const animation = {
  durationFast: '150ms',
  durationNormal: '300ms',
  durationSlow: '500ms',
  easingDefault: 'cubic-bezier(0.4, 0, 0.2, 1)'
} as const;
`.trim();

    const tailwindConfigContent = `
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}'
  ],
  theme: {
    extend: {
      colors: {
        brandPrimary: '${colors.primary}',
        brandSecondary: '${colors.secondary}',
        brandAccent: '${colors.accent}',
        brandSurface: '${colors.surface}',
        brandBackground: '${colors.background}'
      },
      fontFamily: {
        heading: ['${headingFont}'],
        body: ['${bodyFont}']
      }
    }
  },
  plugins: []
};
`.trim();

    return [
      {
        path: 'src/tokens/index.ts',
        content: indexContent,
        language: 'typescript',
        type: 'token'
      },
      {
        path: 'tailwind.config.js',
        content: tailwindConfigContent,
        language: 'javascript',
        type: 'config'
      }
    ];
  }
}
