import { KnowledgeRecord } from './KnowledgeTypes';

export class KnowledgeLoader {
  /**
   * Generates a comprehensive seed dataset spanning all 24 Knowledge Categories
   * with strict schemas, quality scores, and graph relationships.
   */
  public static loadSeedData(): KnowledgeRecord[] {
    const now = Date.now();

    return [
      // 1. Design Systems
      {
        id: 'ds-modern-saas',
        title: 'Modern SaaS Design System',
        category: 'design-systems',
        subcategory: 'Modern SaaS',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Scalable B2B SaaS web applications',
        description: 'Clean design system optimized for high-density dashboards and conversion pages.',
        tags: ['saas', 'modern', 'clean', 'b2b'],
        keywords: ['system', 'tokens', 'components', 'responsive'],
        qualityScore: 95,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.8, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [
          { sourceId: 'ds-modern-saas', type: 'contains', targetId: 'comp-navbar-primary', weight: 1.0 },
          { sourceId: 'ds-modern-saas', type: 'contains', targetId: 'comp-hero-split', weight: 1.0 },
          { sourceId: 'ds-modern-saas', type: 'uses', targetId: 'color-palette-indigo', weight: 0.9 }
        ],
        version: '1.0.0',
        createdAt: now - 86400000 * 30,
        updatedAt: now,
        source: 'Internal Knowledge Repository',
        license: 'MIT',
        status: 'active'
      },
      {
        id: 'ds-sleek-dark',
        title: 'Sleek Dark Minimal System',
        category: 'design-systems',
        subcategory: 'Enterprise',
        industry: 'Developer Tools',
        style: 'Minimal',
        purpose: 'Developer tools, IDEs, and technical dashboards',
        description: 'High-contrast dark theme design system with subtle glass accents.',
        tags: ['dark-mode', 'developer', 'ide', 'minimal'],
        keywords: ['dark', 'sleek', 'high-contrast', 'glow'],
        qualityScore: 92,
        difficulty: 'advanced',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 7.2, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [
          { sourceId: 'ds-sleek-dark', type: 'contains', targetId: 'comp-button-primary', weight: 0.9 }
        ],
        version: '1.0.0',
        createdAt: now - 86400000 * 20,
        updatedAt: now,
        source: 'Internal Knowledge Repository',
        license: 'MIT',
        status: 'active'
      },

      // 2. UI Components
      {
        id: 'comp-navbar-primary',
        title: 'Sticky Navigation Bar',
        category: 'ui-components',
        subcategory: 'Navbar',
        industry: 'General',
        style: 'Modern',
        purpose: 'Top-level app navigation with responsive hamburger menu',
        description: 'Fixed top header with logo, navigation links, and primary CTA button.',
        tags: ['navbar', 'navigation', 'header', 'sticky'],
        keywords: ['menu', 'brand', 'links', 'cta'],
        qualityScore: 94,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [
          { sourceId: 'comp-navbar-primary', type: 'uses', targetId: 'comp-button-primary', weight: 0.8 }
        ],
        version: '1.0.0',
        createdAt: now - 86400000 * 25,
        updatedAt: now,
        source: 'UI Patterns Spec',
        license: 'MIT',
        status: 'active'
      },
      {
        id: 'comp-hero-split',
        title: 'Split Hero Section with Media',
        category: 'ui-components',
        subcategory: 'Hero',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'High-impact landing page entrance section',
        description: 'Left side title, subtitle, and CTA buttons paired with right side app preview image.',
        tags: ['hero', 'landing', 'header', 'banner'],
        keywords: ['heading', 'cta', 'preview', 'illustration'],
        qualityScore: 96,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 5.1, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [
          { sourceId: 'comp-hero-split', type: 'uses', targetId: 'comp-button-primary', weight: 1.0 }
        ],
        version: '1.1.0',
        createdAt: now - 86400000 * 15,
        updatedAt: now,
        source: 'SaaS Design Guidelines',
        license: 'MIT',
        status: 'active'
      },
      {
        id: 'comp-button-primary',
        title: 'Primary Solid Action Button',
        category: 'ui-components',
        subcategory: 'Button',
        industry: 'General',
        style: 'Modern',
        purpose: 'Primary user action call-to-action',
        description: 'High-contrast filled button with focus indicator and loading state support.',
        tags: ['button', 'cta', 'input', 'action'],
        keywords: ['click', 'submit', 'primary', 'hover'],
        qualityScore: 98,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 8.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 40,
        updatedAt: now,
        source: 'Component Specs',
        license: 'MIT',
        status: 'active'
      },

      // 3. Layout Patterns
      {
        id: 'layout-landing-saas',
        title: 'SaaS Landing Page Structure',
        category: 'layout-patterns',
        subcategory: 'Landing Page',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Product landing page with features, pricing, and testimonials',
        description: 'Standard 7-section vertical layout for SaaS product marketing.',
        tags: ['landing', 'layout', 'saas', 'page'],
        keywords: ['hero', 'features', 'pricing', 'footer'],
        qualityScore: 93,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.6, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [
          { sourceId: 'layout-landing-saas', type: 'contains', targetId: 'comp-navbar-primary', weight: 1.0 },
          { sourceId: 'layout-landing-saas', type: 'contains', targetId: 'comp-hero-split', weight: 1.0 }
        ],
        version: '1.0.0',
        createdAt: now - 86400000 * 10,
        updatedAt: now,
        source: 'Landing Page Blueprint Archive',
        license: 'MIT',
        status: 'active'
      },

      // 4. UX Patterns
      {
        id: 'ux-auth-flow',
        title: 'Multi-Factor Authentication Flow',
        category: 'ux-patterns',
        subcategory: 'Authentication',
        industry: 'Security',
        style: 'Minimal',
        purpose: 'Secure user login and identity verification',
        description: 'Two-step authentication flow with SMS/TOTP fallback options.',
        tags: ['auth', 'login', 'security', 'otp'],
        keywords: ['password', 'mfa', 'signin', 'verification'],
        qualityScore: 90,
        difficulty: 'advanced',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.8, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 12,
        updatedAt: now,
        source: 'Security UX Handbook',
        license: 'MIT',
        status: 'active'
      },

      // 5. Industry Templates
      {
        id: 'ind-fintech-dashboard',
        title: 'Fintech Analytics Platform Template',
        category: 'industry-templates',
        subcategory: 'Finance',
        industry: 'Finance',
        style: 'Dashboard',
        purpose: 'Financial monitoring and portfolio management interface',
        description: 'High-density grid layout with stock tickers, KPI cards, and interactive line charts.',
        tags: ['finance', 'fintech', 'analytics', 'dashboard'],
        keywords: ['stocks', 'charts', 'kpi', 'portfolio'],
        qualityScore: 96,
        difficulty: 'advanced',
        deviceSupport: ['desktop', 'tablet'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 5.2, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: false, stackingStrategy: 'grid' },
        relationships: [],
        version: '1.2.0',
        createdAt: now - 86400000 * 18,
        updatedAt: now,
        source: 'Fintech UI Guidelines',
        license: 'MIT',
        status: 'active'
      },

      // 6. Design Styles
      {
        id: 'style-glassmorphism',
        title: 'Glassmorphism Surface Aesthetics',
        category: 'design-styles',
        subcategory: 'Glass',
        industry: 'Creative',
        style: 'Glass',
        purpose: 'Translucent layered UI cards and navigation panels',
        description: 'Backdrop-filter blur, semi-transparent white border, and subtle glow shadows.',
        tags: ['glass', 'glassmorphism', 'translucent', 'backdrop'],
        keywords: ['blur', 'alpha', 'transparency', 'glow'],
        qualityScore: 88,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 22,
        updatedAt: now,
        source: 'Modern Web Guidance',
        license: 'MIT',
        status: 'active'
      },

      // 7. Color Knowledge
      {
        id: 'color-palette-indigo',
        title: 'Indigo Tech SaaS Palette',
        category: 'color-knowledge',
        subcategory: 'Primary',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Accessible 60-30-10 color scheme for SaaS applications',
        description: 'Primary Indigo (#4f46e5), Secondary Slate (#64748b), Accent Cyan (#06b6d4), Surface Dark (#0f172a).',
        tags: ['colors', 'palette', 'indigo', 'accessible'],
        keywords: ['primary', 'secondary', 'accent', 'contrast'],
        qualityScore: 97,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 8.2, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 50,
        updatedAt: now,
        source: 'Color Science Engine',
        license: 'MIT',
        status: 'active'
      },

      // 8. Typography Knowledge
      {
        id: 'typo-inter-scale',
        title: 'Inter Modular Typography Scale',
        category: 'typography-knowledge',
        subcategory: 'Heading Scale',
        industry: 'General',
        style: 'Modern',
        purpose: 'Perfect fourth (1.333) typographic scale for web interfaces',
        description: 'Display (48px), H1 (36px), H2 (27px), H3 (20px), Body (15px), Caption (12px).',
        tags: ['typography', 'inter', 'font', 'scale'],
        keywords: ['heading', 'body', 'line-height', 'hierarchy'],
        qualityScore: 95,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 10.0, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 60,
        updatedAt: now,
        source: 'Typography Planner',
        license: 'MIT',
        status: 'active'
      },

      // 9. Animation Knowledge
      {
        id: 'anim-button-hover',
        title: 'Button Spring Hover Effect',
        category: 'animation-knowledge',
        subcategory: 'Hover',
        industry: 'General',
        style: 'Modern',
        purpose: 'Interactive hover feedback on primary action controls',
        description: 'Scale 1.03 with cubic-bezier(0.16, 1, 0.3, 1) and sub-pixel glow shadow.',
        tags: ['animation', 'hover', 'spring', 'micro-interaction'],
        keywords: ['transition', 'easing', 'scale', 'glow'],
        qualityScore: 92,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 14,
        updatedAt: now,
        source: 'Motion Design Guidelines',
        license: 'MIT',
        status: 'active'
      },

      // 10. Accessibility
      {
        id: 'a11y-wcag-21-aa',
        title: 'WCAG 2.1 AA Compliance Rules',
        category: 'accessibility',
        subcategory: 'WCAG',
        industry: 'General',
        style: 'Corporate',
        purpose: 'Baseline web accessibility standards',
        description: 'Minimum 4.5:1 text contrast ratio, 44x44px touch targets, full keyboard focus rings.',
        tags: ['accessibility', 'wcag', 'a11y', 'compliance'],
        keywords: ['contrast', 'aria', 'focus', 'keyboard'],
        qualityScore: 100,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 7.0, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '2.1.0',
        createdAt: now - 86400000 * 100,
        updatedAt: now,
        source: 'W3C WCAG Guidelines',
        license: 'W3C License',
        status: 'active'
      },

      // 11. Responsive Design
      {
        id: 'resp-grid-breakpoints',
        title: 'Standard Responsive Grid Breakpoints',
        category: 'responsive-design',
        subcategory: 'Desktop',
        industry: 'General',
        style: 'Modern',
        purpose: 'Breakpoint grid system for responsive web applications',
        description: 'Desktop (1200px 12-col), Tablet (768px 6-col), Mobile (375px 2-col).',
        tags: ['responsive', 'grid', 'breakpoints', 'mobile'],
        keywords: ['desktop', 'tablet', 'mobile', 'columns'],
        qualityScore: 94,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile', 'foldable', 'ultrawide'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 45,
        updatedAt: now,
        source: 'Responsive Grid Spec',
        license: 'MIT',
        status: 'active'
      },

      // 12. Dashboard Library
      {
        id: 'dash-analytics-kpi',
        title: 'Executive Analytics KPI Grid',
        category: 'dashboard-library',
        subcategory: 'Analytics',
        industry: 'Analytics',
        style: 'Dashboard',
        purpose: 'Top-level key performance indicator cards with sparklines',
        description: '4-card metric row showing Revenue, Active Users, Conversion Rate, and MRR.',
        tags: ['dashboard', 'kpi', 'analytics', 'metrics'],
        keywords: ['revenue', 'users', 'conversion', 'sparkline'],
        qualityScore: 95,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.8, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 8,
        updatedAt: now,
        source: 'Dashboard Design Systems',
        license: 'MIT',
        status: 'active'
      },

      // 13. SaaS Library
      {
        id: 'saas-pricing-tiers',
        title: '3-Tier SaaS Pricing Table',
        category: 'saas-library',
        subcategory: 'Pricing',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Pricing plan selection card grid with recommended highlighted tier',
        description: 'Starter ($15), Pro ($49 - Featured), Enterprise (Custom) cards with feature checklist.',
        tags: ['saas', 'pricing', 'tiers', 'plans'],
        keywords: ['pro', 'starter', 'checklist', 'featured'],
        qualityScore: 96,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 5.0, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [
          { sourceId: 'saas-pricing-tiers', type: 'uses', targetId: 'comp-button-primary', weight: 1.0 }
        ],
        version: '1.1.0',
        createdAt: now - 86400000 * 7,
        updatedAt: now,
        source: 'SaaS Conversion Kit',
        license: 'MIT',
        status: 'active'
      },

      // 14. AI Product Library
      {
        id: 'ai-chat-interface',
        title: 'Conversational AI Workspace Interface',
        category: 'ai-product-library',
        subcategory: 'Chat',
        industry: 'AI',
        style: 'Modern',
        purpose: 'Interactive AI chat application with prompt bar and history sidebar',
        description: 'Left collapsible conversation history, main message thread with markdown rendering, and bottom input box.',
        tags: ['ai', 'chat', 'llm', 'workspace'],
        keywords: ['prompt', 'copilot', 'history', 'messages'],
        qualityScore: 97,
        difficulty: 'advanced',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.7, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 5,
        updatedAt: now,
        source: 'AI Product UI Standards',
        license: 'MIT',
        status: 'active'
      },

      // 15. E-commerce Library
      {
        id: 'ecom-product-card',
        title: 'Product Catalog Grid Card',
        category: 'ecommerce-library',
        subcategory: 'Product',
        industry: 'Retail',
        style: 'Minimal',
        purpose: 'Product thumbnail card with quick-add to cart button',
        description: 'Aspect ratio image container, title, star rating, price, and floating cart icon button.',
        tags: ['ecommerce', 'product', 'card', 'shop'],
        keywords: ['price', 'rating', 'cart', 'image'],
        qualityScore: 92,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.6, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'grid' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 11,
        updatedAt: now,
        source: 'Storefront Specs',
        license: 'MIT',
        status: 'active'
      },

      // 16. Forms Library
      {
        id: 'form-login-card',
        title: 'Centered Sign-in Form',
        category: 'forms-library',
        subcategory: 'Login',
        industry: 'General',
        style: 'Minimal',
        purpose: 'User authentication login card with OAuth buttons',
        description: 'Email & password inputs, remember me checkbox, forgot password link, and Google/GitHub login.',
        tags: ['form', 'login', 'signup', 'auth'],
        keywords: ['email', 'password', 'oauth', 'remember'],
        qualityScore: 94,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 7.1, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [
          { sourceId: 'form-login-card', type: 'uses', targetId: 'comp-button-primary', weight: 1.0 }
        ],
        version: '1.0.0',
        createdAt: now - 86400000 * 16,
        updatedAt: now,
        source: 'Form Architecture Spec',
        license: 'MIT',
        status: 'active'
      },

      // 17. Charts
      {
        id: 'chart-line-gradient',
        title: 'Gradient Area Metric Line Chart',
        category: 'charts',
        subcategory: 'Line',
        industry: 'Analytics',
        style: 'Dashboard',
        purpose: 'Time-series trend analysis data visualization',
        description: 'Smooth curved spline line chart with subtle gradient fill under the line and hover tooltips.',
        tags: ['chart', 'line', 'analytics', 'graph'],
        keywords: ['spline', 'gradient', 'tooltip', 'time-series'],
        qualityScore: 93,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: false, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 9,
        updatedAt: now,
        source: 'Viz Library',
        license: 'MIT',
        status: 'active'
      },

      // 18. Icons
      {
        id: 'icon-usage-guidelines',
        title: 'System Vector Icon Rules',
        category: 'icons',
        subcategory: 'Usage Rules',
        industry: 'General',
        style: 'Modern',
        purpose: 'Icon selection, 24px stroke alignment, and sizing standards',
        description: 'Use 24x24px viewBox icons with 2px stroke width. Always provide aria-hidden or title labels.',
        tags: ['icons', 'vector', 'svg', 'symbols'],
        keywords: ['size', 'stroke', 'lucide', 'aria'],
        qualityScore: 91,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 8.0, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 35,
        updatedAt: now,
        source: 'Iconography Standard',
        license: 'MIT',
        status: 'active'
      },

      // 19. Illustrations
      {
        id: 'illus-hero-placeholder',
        title: 'Abstract Vector Hero Scene',
        category: 'illustrations',
        subcategory: 'Hero',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Hero background and product illustration placeholder graphics',
        description: 'Layered geometric shapes with subtle glow effects and floating app card frames.',
        tags: ['illustration', 'hero', 'graphics', 'scene'],
        keywords: ['abstract', 'glow', 'cards', 'banner'],
        qualityScore: 89,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 13,
        updatedAt: now,
        source: 'Illustration Engine',
        license: 'MIT',
        status: 'active'
      },

      // 20. Component States
      {
        id: 'state-button-interactive',
        title: 'Standard Interactive Component States',
        category: 'component-states',
        subcategory: 'Hover',
        industry: 'General',
        style: 'Modern',
        purpose: 'Default, Hover, Active, Focused, and Disabled state specifications',
        description: 'Define clear visual feedback across all 5 interactive component states.',
        tags: ['states', 'interactive', 'hover', 'focus'],
        keywords: ['active', 'disabled', 'loading', 'feedback'],
        qualityScore: 96,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AAA', contrastRatio: 7.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'wrap' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 28,
        updatedAt: now,
        source: 'Design Tokens Spec',
        license: 'MIT',
        status: 'active'
      },

      // 21. UX Research
      {
        id: 'uxr-f-shape-reading',
        title: 'F-Pattern Reading & Scanning Heuristic',
        category: 'ux-research',
        subcategory: 'Reading Patterns',
        industry: 'General',
        style: 'Editorial',
        purpose: 'Optimizing content hierarchy for visual scanning',
        description: 'Users scan web pages in an F-shaped pattern: top horizontal, second horizontal, vertical left stream.',
        tags: ['ux', 'research', 'eye-tracking', 'scanning'],
        keywords: ['f-shape', 'hierarchy', 'headings', 'cta'],
        qualityScore: 94,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 70,
        updatedAt: now,
        source: 'Nielsen Norman Group Research',
        license: 'Public Knowledge',
        status: 'active'
      },

      // 22. Conversion Knowledge
      {
        id: 'conv-above-fold-cta',
        title: 'Above-the-Fold Primary CTA Rule',
        category: 'conversion-knowledge',
        subcategory: 'Landing Pages',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Maximizing landing page visitor conversion rate',
        description: 'Ensure a clear headline, value proposition subtitle, and high-contrast CTA button are visible without scrolling.',
        tags: ['conversion', 'cta', 'landing', 'cro'],
        keywords: ['headline', 'above-fold', 'signup', 'leads'],
        qualityScore: 97,
        difficulty: 'beginner',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 5.0, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 40,
        updatedAt: now,
        source: 'Conversion Optimization Handbook',
        license: 'MIT',
        status: 'active'
      },

      // 23. Design Trends
      {
        id: 'trend-bento-grid',
        title: 'Bento Box Layout Grid Trend',
        category: 'design-trends',
        subcategory: 'Trend Name',
        industry: 'Tech',
        style: 'Modern',
        purpose: 'Modular feature showcasing using asymmetrical grid cards',
        description: 'Grid layout inspired by Japanese bento boxes, grouping distinct features into variable-sized rounded cards.',
        tags: ['trend', 'bento', 'grid', 'features'],
        keywords: ['bento-box', 'cards', 'asymmetrical', 'popular'],
        qualityScore: 92,
        difficulty: 'intermediate',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 4.7, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 4,
        updatedAt: now,
        source: 'UI Trends Report 2026',
        license: 'MIT',
        status: 'active'
      },

      // 24. Generated Designs
      {
        id: 'gen-model-dashboard-v1',
        title: 'Approved Analytics Dashboard Model',
        category: 'generated-designs',
        subcategory: 'Approved Model',
        industry: 'SaaS',
        style: 'Modern',
        purpose: 'Reusable approved design model for SaaS analytics apps',
        description: 'Complete Visual Design Model created from validated user sketch input.',
        tags: ['generated', 'model', 'approved', 'reusable'],
        keywords: ['sketch', 'processed', 'visual-model'],
        qualityScore: 98,
        difficulty: 'advanced',
        deviceSupport: ['desktop', 'tablet', 'mobile'],
        accessibility: { wcagLevel: 'AA', contrastRatio: 5.5, ariaSupported: true, keyboardNavigable: true },
        responsiveSupport: { supportsDesktop: true, supportsTablet: true, supportsMobile: true, stackingStrategy: 'stack' },
        relationships: [],
        version: '1.0.0',
        createdAt: now - 86400000 * 1,
        updatedAt: now,
        source: 'Sketch Analyzer Pipeline',
        license: 'User Content',
        status: 'active'
      }
    ];
  }
}
